name: Deploy To Vscode Marketplace

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Build_Release']
    types:
      - completed

jobs:
  deploy:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies
        run: yarn

      - name: Publish
        run: vsce publish --yarn --skip-duplicate
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
