name: Deploy To Vscode Marketplace

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Publish
        run: yarn deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
